# Based on https://github.com/actions-rs/meta/blob/master/recipes/quickstart.md

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

name: Continuous Integration

jobs:
  check:
    name: Run cargo check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Run cargo check
        run: cargo check --all-targets

      - name: Run cargo check with all feature
        run: cargo check --all-targets --all-features

      - name: Run cargo check headless
        run: cargo check --all-targets --no-default-features

  docs:
    name: Run cargo doc
    env:
      RUSTDOCFLAGS: -D warnings
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Run cargo doc
        run: cargo doc --features="inspect" --no-deps

  build_examples:
    name: Build examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install Linux dependencies
        run: sudo apt-get update; sudo apt-get install pkg-config libx11-dev libasound2-dev libudev-dev libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev

      - name: Build examples without inspect feature
        run: cargo build --examples --features="ogg"

      - name: Clean
        run: cargo clean

      - name: Build examples with all features
        run: cargo build --examples --all-features

  # test:
  #   name: Tests
  #   strategy:
  #     # Tests are most likely to have OS-specific behavior
  #     matrix:
  #       os: [ubuntu-latest, windows-latest, macOS-latest]

  #   runs-on: ${{ matrix.os }}
  #   steps:
  #     - name: Checkout sources
  #       uses: actions/checkout@v3

  #     - name: Install stable toolchain
  #       uses: dtolnay/rust-toolchain@stable

  #     - name: Install Linux dependencies
  #       if: ${{ matrix.os == 'ubuntu-latest' }}
  #       run: sudo apt-get install --no-install-recommends libwayland-dev libxkbcommon-dev

  #     - name: Run cargo test
  #       run: cargo test
